gvfs-gdu-volume-monitor: Add missing build dependency on GTK
Fixes errors like
git/daemon/gvfsbackendrecent.c:15:21: fatal error: gtk/gtk.h: No such
file or directory
|  #include <gtk/gtk.h>

Signed-off-by: Khem Raj <raj.khem@gmail.com>